[options]
    UseSyslog
    Interface = eth0

[openSSH_API]
    sequence      = 7000,8000,9000
    tcpflags      = syn
    seq_timeout   = 10
    cmd_timeout   = 300
    start_command = /sbin/iptables -I INPUT -s %IP% -p tcp --dport 22 -j ACCEPT
    stop_command  = /sbin/iptables -D INPUT -s %IP% -p tcp --dport 22 -j ACCEPT
    tcp